#!/usr/bin/env python3
"""Fetch skill folders from remote git repositories, as listed in a config file.

The target repositories are expected to follow the same layout as this
project (GitHub Copilot harness), i.e. skills live under
``.github/skills/<name>``. For each configured source, this script resolves
the configured revision (branch, tag, or commit) to an exact git commit,
compares it against ``fetch_skills.lock``, and only re-fetches a skill when
its resolved commit differs from the locked one (or the local copy is
missing). The lock file always records the concrete commit hash, even when
the config points at a branch or tag, so re-runs are reproducible and
changes are explicit.

All configuration lives in ``fetch_skills.yaml`` next to this script - the
script itself takes no parameters. See that file for the config schema.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

CONFIG_PATH = Path(__file__).parent / "fetch_skills.yaml"
LOCK_PATH = Path(__file__).parent / "fetch_skills.lock"
SKILLS_SUBPATH = ".github/skills"
COMMIT_SHA_RE = re.compile(r"^[0-9a-f]{40}$", re.IGNORECASE)


def run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    """Run a subprocess, raising with readable output on failure."""
    result = subprocess.run(cmd, capture_output=True, text=True, **kwargs)
    if result.returncode != 0:
        raise RuntimeError(
            f"Command failed: {' '.join(cmd)}\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )
    return result


def load_config(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    if not config or "destination" not in config or "sources" not in config:
        raise ValueError(
            f"Config at {path} must define 'destination' and 'sources'"
        )
    return config


def load_lock(path: Path) -> dict[tuple[str, str, str], dict]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return {
        (entry["space"], entry["repo"], entry["skill"]): entry
        for entry in data.get("skills", [])
    }


def save_lock(path: Path, lock: dict[tuple[str, str, str], dict]) -> None:
    entries = sorted(lock.values(), key=lambda e: (e["space"], e["repo"], e["skill"]))
    with path.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by fetch_skills.py - do not edit by hand.\n")
        yaml.safe_dump({"skills": entries}, f, sort_keys=False)


def build_repo_url(space: str, repo: str) -> str:
    return space.rstrip("/") + "/" + repo


def resolve_commit(url: str, ref: str) -> str:
    """Resolve a branch/tag/commit reference to a concrete, full commit hash."""
    if COMMIT_SHA_RE.match(ref):
        return ref.lower()

    result = run(["git", "ls-remote", url, ref])
    refs: dict[str, str] = {}
    for line in result.stdout.splitlines():
        sha, _, name = line.partition("\t")
        if sha and name:
            refs[name] = sha

    for candidate in (f"refs/tags/{ref}^{{}}", f"refs/tags/{ref}", f"refs/heads/{ref}"):
        if candidate in refs:
            return refs[candidate]
    if len(refs) == 1:
        return next(iter(refs.values()))

    raise RuntimeError(f"Could not resolve ref '{ref}' in {url}")


def fetch_skill_files(url: str, commit: str, skills: list[str], dest: Path) -> list[str]:
    """Fetch the given skills at an exact commit into dest. Returns skills actually copied."""
    skill_relpaths = {skill: f"{SKILLS_SUBPATH}/{skill}" for skill in skills}
    fetched: list[str] = []

    with tempfile.TemporaryDirectory(prefix="fetch-skill-") as tmp_dir:
        tmp_path = Path(tmp_dir)

        print(f"  Fetching commit {commit[:8]} from {url} ...")
        run(["git", "init", "-q", str(tmp_path)])
        run(["git", "-C", str(tmp_path), "remote", "add", "origin", url])
        run([
            "git", "-C", str(tmp_path), "fetch", "--depth", "1",
            "--filter=blob:none", "origin", commit,
        ])
        run(["git", "-C", str(tmp_path), "checkout", "FETCH_HEAD", "--", *skill_relpaths.values()])

        dest.mkdir(parents=True, exist_ok=True)

        for skill, relpath in skill_relpaths.items():
            source = tmp_path / relpath
            if not source.is_dir():
                print(
                    f"  Warning: skill '{skill}' not found at '{relpath}' "
                    f"in {url}@{commit[:8]}, skipping",
                    file=sys.stderr,
                )
                continue

            target = dest / skill
            if target.exists():
                shutil.rmtree(target)

            shutil.copytree(source, target)
            fetched.append(skill)

    return fetched


def main() -> int:
    try:
        config = load_config(CONFIG_PATH)
    except (OSError, ValueError, yaml.YAMLError) as exc:
        print(f"Error loading config {CONFIG_PATH}: {exc}", file=sys.stderr)
        return 1

    lock = load_lock(LOCK_PATH)
    dest = Path(config["destination"])
    had_error = False

    for entry in config["sources"]:
        try:
            space = entry["space"]
            repo, ref = entry["source"].split(":", 1)
            skills = entry["skills"]
        except (KeyError, ValueError) as exc:
            print(f"Error: malformed source entry {entry}: {exc}", file=sys.stderr)
            had_error = True
            continue

        url = build_repo_url(space, repo)
        try:
            commit = resolve_commit(url, ref)
        except RuntimeError as exc:
            print(f"Error resolving {url}@{ref}: {exc}", file=sys.stderr)
            had_error = True
            continue

        stale: list[str] = []
        for skill in skills:
            key = (space, repo, skill)
            locked = lock.get(key)
            if locked and locked.get("commit") == commit and (dest / skill).is_dir():
                print(f"Skill '{skill}' is up to date (commit {commit[:8]}), skipping.")
                continue
            stale.append(skill)

        if not stale:
            continue

        try:
            fetched = fetch_skill_files(url, commit, stale, dest)
        except RuntimeError as exc:
            print(f"Error fetching from {url}@{ref}: {exc}", file=sys.stderr)
            had_error = True
            continue

        for skill in fetched:
            key = (space, repo, skill)
            previous = lock.get(key)
            lock[key] = {
                "space": space,
                "repo": repo,
                "skill": skill,
                "ref": ref,
                "commit": commit,
            }
            if previous and previous.get("commit") not in (None, commit):
                print(
                    f"Skill '{skill}' CHANGED: {previous['commit'][:8]} -> {commit[:8]}"
                )
            elif previous:
                print(f"Skill '{skill}' re-fetched (local copy was missing).")
            else:
                print(f"Skill '{skill}' fetched for the first time (commit {commit[:8]}).")

    save_lock(LOCK_PATH, lock)
    print("Done." if not had_error else "Done, with errors.")
    return 1 if had_error else 0


if __name__ == "__main__":
    raise SystemExit(main())
